name: CI
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting up the environment
      run: npm install && npm run build
    - name: Running unit tests
      run: npm run unit-tests -- --clientId=${secrets.CLIENTID} --clientSecret=${secrets.CLIENTSECRET} --username=${secrets.EMAIL} --password=${secrets.EMAILPASSWORD} --scope=https://www.googleapis.com/auth/gmail.readonly --debug=false